version: "3.9"
services:
  db:
    image: postgres
    container_name: app-db
    environment:
      - POSTGRES_DB=spotter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app-api
    restart: unless-stopped
    environment:
      - APP_PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=spotter
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db